{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ss7-ha-gateway.fullname" . }}-pdb
  labels:
    {{- include "ss7-ha-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ss7-ha-gateway.selectorLabels" . | nindent 6 }}
{{- end -}}
