{{- if .Values.k8s.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ss7-ha-gateway.serviceAccountName" . }}
  labels:
    {{- include "ss7-ha-gateway.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ss7-ha-gateway.fullname" . }}-role
  labels:
    {{- include "ss7-ha-gateway.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.k8s.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ss7-ha-gateway.fullname" . }}-rolebinding
  labels:
    {{- include "ss7-ha-gateway.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ss7-ha-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ss7-ha-gateway.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
